apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: base
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.24.3
    releaseName: istio-base
    namespace: istio-system
    includeCRDs: true
  - name: istiod
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.24.3
    releaseName: istiod
    namespace: istio-system
    valuesInline:
      meshConfig:
        enableAutoMtls: false
patches:
  - target:
      kind: MutatingWebhookConfiguration
      name: istio-sidecar-injector
    patch: |
      - op: replace
        path: /webhooks/0/failurePolicy
        value: Ignore

resources:
  - namespace.yaml
  - peer-authentication.yaml
