name: node-exporter
image:
  repository: prom/node-exporter
  tag: v1.8.2
service:
  port: 9100
resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 64Mi
tolerations:
  - effect: NoSchedule
    operator: Exists
