apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: argo-rollouts
    repo: https://argoproj.github.io/argo-helm
    version: 2.37.7
    releaseName: argo-rollouts
    namespace: argocd
    includeCRDs: true
    valuesInline:
      dashboard:
        enabled: true
resources:
  - namespace.yaml
  - argocd-httproute.yaml
  - argo-rollouts-httproute.yaml
  - argo-rollouts-backend-policy.yaml
