{{- $root := . -}}
{{- range .Values.instances }}
{{- $port := (.service.port | default 6379) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  namespace: {{ $root.Release.Namespace }}
spec:
  type: {{ .service.type | default "ClusterIP" }}
  selector:
    statefulset.kubernetes.io/pod-name: {{ .name }}-0
  ports:
    - port: {{ $port }}
      targetPort: {{ $port }}
      {{- if .service.nodePort }}
      nodePort: {{ .service.nodePort }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-ro
  namespace: {{ $root.Release.Namespace }}
spec:
  selector:
    app: {{ .name }}
  ports:
    - port: {{ $port }}
      targetPort: {{ $port }}
{{- end }}
