{{- $root := . -}}
{{- range .Values.instances }}
{{- $port := dig "service" "port" 6379 . }}
{{- $serviceType := dig "service" "type" "ClusterIP" . }}
{{- $nodePort := dig "service" "nodePort" nil . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  namespace: {{ $root.Release.Namespace }}
spec:
  type: {{ $serviceType }}
  selector:
    statefulset.kubernetes.io/pod-name: {{ .name }}-0
  ports:
    - port: {{ $port }}
      targetPort: {{ $port }}
      {{- if $nodePort }}
      nodePort: {{ $nodePort }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-ro
  namespace: {{ $root.Release.Namespace }}
spec:
  selector:
    app: {{ .name }}
  ports:
    - port: {{ $port }}
      targetPort: {{ $port }}
{{- end }}
