name: httpbin
image:
  repository: kong/httpbin
  tag: "0.2.3"
replicaCount: 2
rollout:
  strategy: ReplicaCanary
  steps:
    - setWeight: 25
    - pause: {}
    - setWeight: 50
    - pause: {}
    - setWeight: 75
    - pause: {}
service:
  ports:
    - port: 80
      containerPort: 80
httpRoute:
  enabled: true
  host: httpbin.mazino2d-k3s.duckdns.org
instrumentation:
  enabled: true
resources:
  requests:
    cpu: 10m
    memory: 96Mi
  limits:
    memory: 128Mi
