name: outline
image:
  repository: outlinewiki/outline
  tag: "1.7.1"
replicaCount: 1
service:
  port: 3000
  containerPort: 3000
httpRoute:
  enabled: true
  host: outline.mazino2d-k3s.duckdns.org
env:
  URL: http://outline.mazino2d-k3s.duckdns.org
  FORCE_HTTPS: "false"
  FILE_STORAGE: local
  FILE_STORAGE_LOCAL_ROOT_DIR: /var/lib/outline/data
  REDIS_URL: redis://outline-cache-1.apps.svc.cluster.local:6379
  PGSSLMODE: disable
infisical:
  enabled: true
  projectSlug: everything-as-code
  envSlug: dev
envFromSecrets:
  - SECRET_KEY=outline-env:SECRET_KEY
  - UTILS_SECRET=outline-env:UTILS_SECRET
  - OUTLINE_DB_PASSWORD=outline-db-1-auth:POSTGRES_PASSWORD
  - DATABASE_URL=postgres://postgres:$(OUTLINE_DB_PASSWORD)@outline-db-1.apps.svc.cluster.local:5432/postgres
resources:
  requests:
    cpu: 150m
    memory: 512Mi
  limits:
    memory: 1Gi
statefulset:
  enabled: true
  storage:
    enabled: true
    size: 2Gi
    mountPath: /var/lib/outline/data
