apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: grafana-alloy
  namespace: monitoring
spec:
  hostAPI: https://app.infisical.com/api
  syncConfig:
    resyncInterval: "60"
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: everything-as-code
        envSlug: dev
        secretsPath: /monitoring/grafana-alloy
      credentialsRef:
        secretName: infisical-machine-identity
        secretNamespace: infisical-operator
  managedKubeSecretReferences:
    - secretName: grafana-alloy
      secretNamespace: monitoring
      creationPolicy: Orphan
      secretType: Opaque
