apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - networkpolicy-argocd.yaml
helmGlobals:
  chartHome: ../../../../charts
helmCharts:
  - name: eac-app
    releaseName: cloudflared
    namespace: cloudflared
    valuesFile: values.yaml
