apiVersion: v1
kind: ServiceAccount
metadata:
  name: dnsync
  namespace: duckdns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dnsync-reader
rules:
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["gateways"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dnsync-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dnsync-reader
subjects:
  - kind: ServiceAccount
    name: dnsync
    namespace: duckdns
