apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
helmGlobals:
  chartHome: ../../../charts
resources:
  - namespace.yaml
  - hotrod
  - httpbin
  - dagster
helmCharts:
  - name: eac-postgresql
    releaseName: postgresql
    valuesFile: postgresql.yml
    valuesInline:
      infisical:
        projectSlug: everything-as-code
        envSlug: dev
