apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmGlobals:
  chartHome: ../../../charts
resources:
  - namespace.yaml
  - whoami
helmCharts:
  - name: eac-redis
    releaseName: redis
    namespace: apps
    valuesFile: redis.yml
