instances:
  - name: outline-cache-1
    replicaCount: 1
    image:
      tag: "7-alpine"
    storage:
      size: 200Mi
      mountPath: /data
    resources:
      requests:
        cpu: 10m
        memory: 16Mi
      limits:
        memory: 128Mi
    redis:
      maxmemory: "100mb"
      maxmemoryPolicy: "allkeys-lru"
      appendonly: "yes"
      save: "900 1 300 10"
    exporter:
      enabled: true
