name: hotrod
image:
  repository: jaegertracing/example-hotrod
  tag: 2.17.0
replicaCount: 1
service:
  port: 8080
  containerPort: 8080
httpRoute:
  enabled: true
  host: hotrod.mazino2d-k3s.duckdns.org
env:
  OTEL_EXPORTER_OTLP_ENDPOINT: http://grafana-alloy.monitoring.svc.cluster.local:4318
resources:
  requests:
    cpu: 50m
    memory: 64Mi
