name: hotrod
image:
  repository: jaegertracing/example-hotrod
  tag: 2.18.0
workload: deployment
deployment:
  replicaCount: 1
  rollout:
    strategy: BlueGreen
service:
  ports:
    - port: 8080
      containerPort: 8080
httpRoute:
  enabled: true
  host: hotrod.mazino2d-k3s.duckdns.org
env:
  OTEL_EXPORTER_OTLP_ENDPOINT: http://grafana-alloy.monitoring.svc.cluster.local:4318
resources:
  requests:
    cpu: 10m
    memory: 48Mi
  limits:
    memory: 64Mi
