name: ""
replicaCount: 1
image:
  repository: ""
  tag: latest
service:
  type: ""
  port: 80
  containerPort: 80
  nodePort: null
ingress:
  enabled: false
  className: traefik
  host: ""
  annotations: {}
  tls:
    enabled: true
    secretName: ""
    clusterIssuer: letsencrypt-staging
env: {}
infisical:
  enabled: false
  projectSlug: ""
  envSlug: dev
  hostAPI: https://app.infisical.com/api
  resyncInterval: 60
  secretsPath: ""
  managedSecretName: ""
  credentialsRef:
    secretName: infisical-machine-identity
    secretNamespace: infisical-operator
# envFromSecrets supports two formats:
# - "my-secret" (inject all keys from secret via envFrom.secretRef)
# - "DATABASE_URL=my-secret:DATABASE_URL" (inject one key as a specific env var)
# - "DATABASE_URL=postgres://postgres:$(DB_PASSWORD)@db.apps.svc.cluster.local:5432/postgres" (inject literal env value)
envFromSecrets: []
podAnnotations: {}
instrumentation:
  enabled: false
  endpoint: http://grafana-alloy.monitoring.svc.cluster.local:4318
resources:
  requests:
    cpu: 10m
    memory: 64Mi
statefulset:
  enabled: false
  command: []
  args: []
  storage:
    enabled: false
    size: 1Mi
    mountPath: /data
