name: counter
image:
  repository: redis
  tag: "7-alpine"
replicaCount: 2
service:
  type: NodePort
  port: 6379
  containerPort: 6379
  nodePort: 30379
statefulset:
  enabled: true
  storage:
    enabled: true
    size: 100Mi
    mountPath: /data
resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    memory: 64Mi
