{{- $argoStrategies := list "BlueGreen" "ReplicaCanary" "MeshTrafficCanary" }}
{{- if and (not .Values.statefulset.enabled) (not (has .Values.rollout.strategy $argoStrategies)) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.rollout.strategy | default "RollingUpdate" }}
    {{- if eq (.Values.rollout.strategy | default "RollingUpdate") "RollingUpdate" }}
    rollingUpdate:
      maxSurge: {{ .Values.rollout.maxSurge | default 1 }}
      maxUnavailable: {{ .Values.rollout.maxUnavailable | default 0 }}
    {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
      {{- if or .Values.podAnnotations .Values.instrumentation.enabled }}
      annotations:
        {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
        {{- if .Values.instrumentation.enabled }}
        instrumentation.opentelemetry.io/inject-python: {{ .Values.name }}
        {{- end }}
      {{- end }}
    spec:
      {{- include "eac-app.podSpec" . | nindent 6 }}
{{- end }}
