{{- if .Values.httpRoute.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ .Values.httpRoute.gatewayName | default "eac" }}
      namespace: {{ .Values.httpRoute.gatewayNamespace | default "apps" }}
  hostnames:
    - {{ .Values.httpRoute.host }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - group: ""
          kind: Service
          name: {{ .Values.name }}
          port: {{ (index .Values.service.ports 0).port }}
          weight: 1
{{- end }}
