{{- if and .Values.infisical.enabled .Values.infisical.projectSlug }}
{{- $secretsPath := .Values.infisical.secretsPath | default (printf "/%s/%s" .Release.Namespace .Values.name) }}
{{- $managedSecretName := .Values.infisical.managedSecretName | default (printf "%s-env" .Values.name) }}
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  hostAPI: {{ .Values.infisical.hostAPI }}
  syncConfig:
    resyncInterval: {{ .Values.infisical.resyncInterval }}
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: {{ .Values.infisical.projectSlug }}
        envSlug: {{ .Values.infisical.envSlug }}
        secretsPath: {{ $secretsPath }}
      credentialsRef:
        secretName: {{ .Values.infisical.credentialsRef.secretName }}
        secretNamespace: {{ .Values.infisical.credentialsRef.secretNamespace }}
  managedKubeSecretReferences:
    - secretName: {{ $managedSecretName }}
      secretNamespace: {{ .Release.Namespace }}
{{- end }}
