{{- if .Values.instrumentation.enabled }}
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  exporter:
    endpoint: {{ .Values.instrumentation.endpoint }}
  propagators:
    - tracecontext
    - baggage
  python: {}
{{- end }}
