{{- if and (eq .Values.workload "deployment") (eq .Values.deployment.rollout.strategy "BlueGreen") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-preview
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
    {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .containerPort }}
      protocol: TCP
      {{- if .name }}
      name: {{ .name }}
      {{- end }}
    {{- end }}
{{- end }}
