{{- if and (not .Values.statefulset.enabled) (eq .Values.rollout.strategy "BlueGreen") }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
      {{- if or .Values.podAnnotations .Values.instrumentation.enabled }}
      annotations:
        {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
        {{- if .Values.instrumentation.enabled }}
        instrumentation.opentelemetry.io/inject-python: {{ .Values.name }}
        {{- end }}
      {{- end }}
    spec:
      {{- include "eac-app.podSpec" . | nindent 6 }}
  strategy:
    blueGreen:
      activeService: {{ .Values.name }}
      previewService: {{ .Values.name }}-preview
      autoPromotionEnabled: {{ .Values.rollout.autoPromotionEnabled }}
      scaleDownDelaySeconds: {{ .Values.rollout.scaleDownDelaySeconds }}
      previewReplicaCount: {{ .Values.rollout.previewReplicaCount }}
{{- end }}
