apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmGlobals:
  chartHome: charts
helmCharts:
  - name: secrets-operator
    repo: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts/
    version: 0.10.32
    releaseName: infisical-operator
    namespace: infra
    valuesFile: values.yaml
