apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infisical-operator
helmGlobals:
  chartHome: charts
helmCharts:
  - name: secrets-operator
    repo: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts/
    version: 0.10.32
    releaseName: infisical-operator
    namespace: infisical-operator
    valuesInline:
      installCRDs: true
patches:
  - target:
      kind: ServiceAccount
      name: infisical-opera-controller-manager
    patch: |-
      - op: add
        path: /metadata/namespace
        value: infisical-operator
  - target:
      kind: Role
      name: infisical-opera-leader-election-role
    patch: |-
      - op: add
        path: /metadata/namespace
        value: infisical-operator
  - target:
      kind: RoleBinding
      name: infisical-opera-leader-election-rolebinding
    patch: |-
      - op: add
        path: /metadata/namespace
        value: infisical-operator
  - target:
      kind: Service
      name: infisical-opera-controller-manager-metrics-service
    patch: |-
      - op: add
        path: /metadata/namespace
        value: infisical-operator
  - target:
      kind: Deployment
      name: infisical-opera-controller-manager
    patch: |-
      - op: add
        path: /metadata/namespace
        value: infisical-operator
resources:
  - namespace.yaml
