apiVersion: db.atlasgo.io/v1alpha1
kind: AtlasSchema
metadata:
  name: app-db-test-schema
  namespace: apps
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  urlFrom:
    secretKeyRef:
      name: app-db-auth
      key: url
  policy:
    lint:
      destructive:
        error: true
  schema:
    configMapKeyRef:
      name: app-db-schema
      key: schema.hcl
