apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
configMapGenerator:
  - name: app-db-schema
    files:
      - schema.hcl
resources:
  - atlasschema.yaml
