name: Terraform Apply

on:
  push:
    branches:
      - main
    paths:
      - "terraform/**"
      - ".github/workflows/tf-apply.yml"
  workflow_dispatch:

jobs:
  apply:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    defaults:
      run:
        working-directory: terraform/github
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.14.8"
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Init
        run: terraform init

      - name: Apply
        run: terraform apply -auto-approve
