apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: velero-gcp-credentials
  namespace: infra
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: everything-as-code
        envSlug: dev
        secretsPath: /workload-gsa-keys/gcp-mazino2d-as-se1-dev/infra-velero
      credentialsRef:
        secretName: infisical-machine-identity
        secretNamespace: infra
  managedSecretReference:
    secretName: velero-gcp-credentials
    secretNamespace: infra
