apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: velero-gcp-credentials
  namespace: velero
spec:
  hostAPI: https://app.infisical.com/api
  syncConfig:
    resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: everything-as-code
        envSlug: dev
        secretsPath: /workload-gsa-keys/gcp-mazino2d-as-se1-dev/velero-velero
      credentialsRef:
        secretName: infisical-machine-identity
        secretNamespace: infisical-operator
  managedKubeSecretReferences:
    - secretName: velero-gcp-credentials
      secretNamespace: velero
