apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: velero
    repo: https://vmware-tanzu.github.io/helm-charts
    version: 12.0.1
    releaseName: velero
    namespace: infra
    includeCRDs: true
    valuesFile: values.yaml
resources:
  - infisical-secret.yaml
