upgradeCRDs: false

configuration:
  backupStorageLocation:
    - name: default
      provider: gcp
      bucket: mazino2d-as-se1-dev-velero-backups-usc1
      default: true
  volumeSnapshotLocation:
    - name: default
      provider: gcp
  extraEnvVars:
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: /credentials/cloud

credentials:
  useSecret: false

extraVolumes:
  - name: velero-gcp-credentials
    secret:
      secretName: velero-gcp-credentials

extraVolumeMounts:
  - name: velero-gcp-credentials
    mountPath: /credentials/cloud
    subPath: gcp_service_account_json
    readOnly: true

initContainers:
  - name: velero-plugin-for-gcp
    image: velero/velero-plugin-for-gcp:v1.13.2
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins

schedules:
  daily:
    schedule: "0 2 * * *"
    template:
      storageLocation: default
      snapshotVolumes: true
      ttl: 168h0m0s
      includedNamespaces:
        - "*"
  weekly:
    schedule: "0 3 * * 0"
    template:
      storageLocation: default
      snapshotVolumes: true
      ttl: 720h0m0s
      includedNamespaces:
        - "*"
